#!/usr/bin/env bash
SINK=$(pactl get-default-sink)
VOLUME=$(pactl get-sink-volume "$SINK" | grep -oP '\d+%' | head -n1)
MUTE=$(pactl get-sink-mute "$SINK" | awk '{print $2}')

if [ "$MUTE" = "yes" ]; then
    echo "VOL Mute"
else
    echo "VOL $VOLUME"
fi

